### ISSUE TITLE
Send to Mini Paint not working in Firefox

### ISSUE THREAD

**Issue by wogam** [0Tick/a1111-mini-paint#8]
Button not working, error found in console below.

`Uncaught TypeError: e is null
    value http://127.0.0.1:7860/file=C:/Users/N/Downloads/stable-diffusion-webui/extensions/a1111-mini-paint/miniPaint/dist/bundle.js:2
    i http://127.0.0.1:7860/file=C:/Users/N/Downloads/stable-diffusion-webui/extensions/a1111-mini-paint/miniPaint/dist/bundle.js:2
`

**Comment by 0Tick** [comment]
I was not able to replicate this bug. Does it still occur?

**Comment by 0Tick** [comment]
I will close this due to inactivitie. If someone has the same issue please writte something here and i will reopen it again

**Comment by Covalent0714** [comment]
I had the same issue. I disabled all extensions and hard reset the UI. The button did not work. I did not get an error trace. It is simply non-functional.

**Comment by christopherquenneville** [comment]
Hi @0Tick, thanks a LOT for this tool. It's a game changer for me. You single handedly made me replace Vizcom lol.

However, I do seem to have the same problem. Both options under Send > Send to Controlnet are not working. I am *suspecting* that this is due to an update from A1111 (version 1.6?) or from Controlnet.

What I can do is send to Image2Image and do a controlnet generation from there so I am still able to work with it.

I would just like to have all of the options I can get from txt2img.

Thanks again!
Good day

**Comment by 0Tick** [comment]
Should be all fixed now.
